name: CDK

on:
  push:
    branches: [ main ]

jobs:
  aws-cdk-synth:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: CDK Synth
      uses: scottbrenner/aws-cdk-action@master
      with:
        args: synth
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CDK_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_SECRET_ACCESS_KEY }}
